create table studentEntity (
id int generated by default as identity primary key,
first_name varchar(50) NOT NULL,
last_name varchar(50)NOT NULL,
age int check ( age > 0 ),
university varchar,
faculty varchar,
time_create timestamp
)